package com.sample
 
import com.sample.DroolsTest.Message;

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end


rule "BONJOUR"
    when
        Message( status != 0 && status != 1, myMessage : message )
    then
        System.out.println( myMessage );
end

rule "coucou"
 when
        Message( test == 0 )
    then
        System.out.println( "message 0 " );
end
